SDK feedback part 2
Telenav-Search/search-ios-sdk pull request #25
Opened 2020-12-28 05:39 UTC by EvgeniyGushchin

- set default limit value to 10 for TNEntityDiscoverBrandParams
- add FacetParameters to the SearchParams
- add facets params to search request
- Apply builder pattern to TNEntitySDKOptions
- add searchOptions property to search params
- move TNEntitySearchOptionIntent to TNEntitySearchOptions
- move TNEntitySDKOptions to separate file
- update folders structure
- add `validation` method to **Params** objects
- fix misspelling

2020-12-28 07:56 UTC, can-wang commented on TelenavEntitySDK/Classes/Configuration/TNEntitySDKOptions.swift
> +    }
Suggest to only support Builder() pattern here and get rid of the init(apiKey....) method.

2020-12-28 09:03 UTC, can-wang requested changes

2020-12-28 09:03 UTC, can-wang commented on TelenavEntitySDK/Classes/Model/Address&Coordinates/TNEntityGeoPoint.swift
> +        return latitude != nil && longitude != nil
Please enhance the validation rules like below:
latitude != nil & latitude in [-90, 90]   && longitude != nill && longitude in [-180, 180]

2020-12-28 11:21 UTC, EvgeniyGushchin commented on TelenavEntitySDK/Classes/Validator.swift
> +
@can-wang if we convert Date to string with this pattern "yyyy-MM-dd'T'HH:mmZ" then we will have something like `2020-12-28T17:17+0600` where +0600 is information about timezone
So I think that my regex is correct.

2020-12-29 03:59 UTC, can-wang commented on TelenavEntitySDK/Classes/Validator.swift
> +
Search REST API only accepts the entry time in two formats:
a. yyyy-MM-ddTHH:mmZ:   time in UTC time zone
b. yyy-MM-ddTHH:mm:  time in local time zone

Format like: 2020-12-12T12:10+0800 is not supported by search API, thus the using above regrex is incorect.

How about changing the entryTime in iOS SDK from string to Date and  convert it to string value in local time format "yyyy-MM-ddTHH:mm" when building the HTTP payload?

2020-12-31 03:18 UTC, can-wang requested changes

2020-12-31 03:18 UTC, can-wang commented on TelenavEntitySDK/Classes/Service/TNEntitySearchService.swift
>              let err = NSError(domain: "", code: 1001, userInfo: ["Description": "Both parameters searchParams and pageContext cannot be nil simultaneously"])
Should it here return TNEntityError ??

2020-12-31 03:18 UTC, can-wang commented on TelenavEntitySDK/Helpers/TNEntityError.swift
> +                return "Invalid api key or api signature"
Pls refine the message as "Invalid API key or signature"

2020-12-31 03:18 UTC, can-wang commented on TelenavEntitySDK/Helpers/TNEntityError.swift
> +        case initializationError
The name of initializationError is not very clear. 
Please rename it to  "ClientNotReadyError"

2020-12-31 03:18 UTC, can-wang commented on TelenavEntitySDK/Helpers/TNEntityError.swift
> +        case customMessage(message: String)
"customMessage" is also not good name for error type.
Please rename it as "serviceError"

2020-12-31 03:18 UTC, can-wang commented on TelenavEntitySDK/Helpers/TNEntityError.swift
> +                return 18401
please change the code from 18401 to 1000

2021-01-07 10:15 UTC, merged